"""actually_add_core_memory

Revision ID: 153865d4b423
Revises: 773a88ef0845
Create Date: 2026-05-23 09:38:50.736168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '153865d4b423'
down_revision: Union[str, Sequence[str], None] = '773a88ef0845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_memory',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('persona', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_core_memory_user_id'), 'core_memory', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_core_memory_user_id'), table_name='core_memory')
    op.drop_table('core_memory')
    # ### end Alembic commands ###
